- hosts: all
  gather_facts: yes
  become: no
  vars_files:
    - vars/vault.yml
    - vars/settings.yml

  tasks:
    - block:
      - name: Initial server setup (security etc.)
        include_role:
          name: jstet.initial_server_setup
        vars:
          extra_packages:
            - python3-pip
            - python-dev
            - python3-venv
            - git           
      become: yes


    
