- hosts: all
  gather_facts: yes
  become: no
  vars_files:
    - vars/settings.yml
    - vars/vault.yml

  tasks:
    - block:
      - name: Initial server setup (security etc.)
        include_role:
          name: jstet.initial_server_setup
        vars:
          extra_packages:
            - python3-pip
            - python3-dev
            - python3-venv  
            - supervisor  
            - git      
            - chromium
      become: yes

    - name: configuring server for script execution
      include_tasks: tasks/script.yml
    
    - name: configuring server for event listener
      include_tasks: tasks/listener.yml
    
    - name: templating supervisor config to server
      become: yes
      template:
        src: templates/script.conf
        dest: /etc/supervisor/conf.d/script.conf
        force: yes
    
    - name: restarting supervisor
      become: yes
      shell: |
        systemctl restart supervisor
    
    - name: tell Supervisor to look for new program configurations
      become: yes
      shell: |
        supervisorctl reread

    - name: telling Supervisor to enact changes
      become: yes
      shell: |
        supervisorctl update

    - name: starting script
      become: yes
      shell: |
        supervisorctl start script



    
