- name: copy ssh_key to server
  copy: 
    src: files/github_ssh_key 
    dest: .ssh/github_ssh_key
    mode: 00600

- name: Recursively remove directory in case script dir already exists
  ansible.builtin.file:
    path: /home/{{  USER  }}/script
    state: absent
  become: yes

- name: Clone script repo
  shell: |
    git -c core.sshCommand='ssh -i .ssh/github_ssh_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' clone git@github.com:{{ GITHUB_REPO }}.git /home/{{  USER  }}/script

- name: Creating log dir
  ansible.builtin.file:
    path: /home/{{  USER  }}/script/{{ OUTPUT_DIR  }}/supervisor_log
    state: directory
    mode: '0755'
   

- name: Setting up environment
  pip: 
    requirements: /home/{{  USER  }}/script/{{  ENTRYPOINT_DIR  }}/requirements.txt
    virtualenv: /home/{{  USER  }}/script/env
    virtualenv_command: 'python3 -m venv'

